/* Xtransdef.h.  Generated by configure.  */
/* Xtransdef.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `fchown' function. */
#define HAVE_FCHOWN 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <netdnet/dn.h> header file. */
/* #undef HAVE_NETDNET_DN_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the `ptsname' function. */
#define HAVE_PTSNAME 1

/* whether sockaddr_in struct has sin_len */
/* #undef HAVE_SOCKADDR_IN_SIN_LEN */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* System supports stick-bit for directories */
#define HAVE_STICKY_DIR_BIT 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/un.h> header file. */
#define HAVE_SYS_UN_H 1

/* Define to 1 if you have the <tiuser.h> header file. */
/* #undef HAVE_TIUSER_H */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <un.h> header file. */
/* #undef HAVE_UN_H */

/* Name of package */
#define PACKAGE "libXtrans"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "keithp@keithp.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libXtrans"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libXtrans 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libXtrans"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.1"
